#!/usr/bin/env python3
"""
WAIS Documentation Drift Checker

Verifies that the WAIS Figma source matches the documented manifest of
expected tokens, styles, and components. Reports drift in either direction:
  - Manifest has entries that don't exist in WAIS (stale docs)
  - WAIS has entries not in manifest (undocumented additions)

Usage:
    python wais-doc-drift-checker.py path/to/wais-manifest.json path/to/wais-actual.json

The "actual" JSON should be generated by running the inventory snippet
(see wais-inventory-snippet.js) in a Figma use_figma call against WAIS source.

Author: Project Coffee (Q3 2026 target)
"""

import json
import sys
from pathlib import Path


def load_manifest(path: Path) -> dict:
    """Load a JSON manifest of expected WAIS state."""
    with open(path) as f:
        return json.load(f)


def diff_sets(expected: set, actual: set, label: str) -> dict:
    """Compare two sets, report missing/extra."""
    missing = expected - actual
    extra = actual - expected
    return {
        "label": label,
        "expected_count": len(expected),
        "actual_count": len(actual),
        "missing_in_actual": sorted(missing),
        "extra_in_actual": sorted(extra),
        "drift_count": len(missing) + len(extra),
    }


def check_drift(manifest: dict, actual: dict) -> dict:
    """Run all drift checks and return a structured report."""
    report = {"sections": []}

    # 1. Variables — check by qualified name
    expected_vars = {v["name"] for v in manifest.get("variables", [])}
    actual_vars = {v["name"] for v in actual.get("variables", [])}
    report["sections"].append(diff_sets(expected_vars, actual_vars, "Variables"))

    # 2. Variable keys — check that documented keys match actual keys
    expected_var_keys = {v["name"]: v["key"] for v in manifest.get("variables", []) if v.get("key")}
    actual_var_keys = {v["name"]: v["key"] for v in actual.get("variables", []) if v.get("key")}
    key_mismatches = []
    for name, expected_key in expected_var_keys.items():
        actual_key = actual_var_keys.get(name)
        if actual_key and actual_key != expected_key:
            key_mismatches.append({"variable": name, "doc_key": expected_key, "actual_key": actual_key})
    report["sections"].append({
        "label": "Variable key drift",
        "drift_count": len(key_mismatches),
        "mismatches": key_mismatches,
    })

    # 3. Text styles
    expected_styles = {s["name"] for s in manifest.get("textStyles", [])}
    actual_styles = {s["name"] for s in actual.get("textStyles", [])}
    report["sections"].append(diff_sets(expected_styles, actual_styles, "Text Styles"))

    # 4. Text style specs — verify documented spec matches actual
    spec_mismatches = []
    for ms in manifest.get("textStyles", []):
        actual_match = next((s for s in actual.get("textStyles", []) if s["name"] == ms["name"]), None)
        if not actual_match:
            continue
        for prop in ["fontSize", "weight"]:
            if ms.get(prop) and actual_match.get(prop) and ms[prop] != actual_match[prop]:
                spec_mismatches.append({
                    "style": ms["name"],
                    "property": prop,
                    "documented": ms[prop],
                    "actual": actual_match[prop],
                })
    report["sections"].append({
        "label": "Text style spec drift",
        "drift_count": len(spec_mismatches),
        "mismatches": spec_mismatches,
    })

    # 5. Components / variant counts
    expected_comps = {c["name"]: c.get("variants", 1) for c in manifest.get("components", [])}
    actual_comps = {c["name"]: c.get("variants", 1) for c in actual.get("components", [])}
    
    comp_drift = []
    for name in expected_comps:
        if name not in actual_comps:
            comp_drift.append({"component": name, "issue": "missing in WAIS"})
        elif expected_comps[name] != actual_comps[name]:
            comp_drift.append({
                "component": name,
                "issue": "variant count differs",
                "documented": expected_comps[name],
                "actual": actual_comps[name],
            })
    for name in actual_comps:
        if name not in expected_comps:
            comp_drift.append({"component": name, "issue": "undocumented in manifest"})
    
    report["sections"].append({
        "label": "Component drift",
        "drift_count": len(comp_drift),
        "issues": comp_drift,
    })

    # 6. Total drift score
    report["total_drift"] = sum(s.get("drift_count", 0) for s in report["sections"])
    report["status"] = "CLEAN" if report["total_drift"] == 0 else "DRIFT_DETECTED"

    return report


def format_report(report: dict) -> str:
    """Pretty-print the drift report."""
    lines = []
    lines.append("=" * 70)
    lines.append(f"WAIS Documentation Drift Report — Status: {report['status']}")
    lines.append(f"Total drift items: {report['total_drift']}")
    lines.append("=" * 70)
    
    for section in report["sections"]:
        lines.append(f"\n── {section['label']} — {section['drift_count']} drift items ──")
        if section.get("expected_count") is not None:
            lines.append(f"  Expected: {section['expected_count']}, Actual: {section['actual_count']}")
        
        if section.get("missing_in_actual"):
            lines.append(f"  ⚠️  Missing in WAIS (documented but not present):")
            for item in section["missing_in_actual"]:
                lines.append(f"    - {item}")
        
        if section.get("extra_in_actual"):
            lines.append(f"  ℹ️  Extra in WAIS (present but not documented):")
            for item in section["extra_in_actual"]:
                lines.append(f"    + {item}")
        
        if section.get("mismatches"):
            lines.append(f"  ⚠️  Spec mismatches:")
            for m in section["mismatches"]:
                lines.append(f"    - {m}")
        
        if section.get("issues"):
            lines.append(f"  ⚠️  Component issues:")
            for i in section["issues"]:
                lines.append(f"    - {i}")
    
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    
    manifest_path = Path(sys.argv[1])
    actual_path = Path(sys.argv[2])
    
    if not manifest_path.exists():
        print(f"Manifest file not found: {manifest_path}", file=sys.stderr)
        sys.exit(1)
    if not actual_path.exists():
        print(f"Actual state file not found: {actual_path}", file=sys.stderr)
        sys.exit(1)
    
    manifest = load_manifest(manifest_path)
    actual = load_manifest(actual_path)
    
    report = check_drift(manifest, actual)
    print(format_report(report))
    
    # Exit non-zero if drift detected (useful for CI)
    sys.exit(0 if report["status"] == "CLEAN" else 1)


if __name__ == "__main__":
    main()
